# ================================
# Ticket Category Settings
# ================================

# Define different categories of tickets here.
# Each category should have a unique identifier.

ticketCategories:
    # Category 1
    category1:
        # Label displayed in the select menu
        menuLabel: 'Category 1'
        # Description explaining the purpose of this category
        menuDescription: 'This category is for general inquiries and questions.'
        # Emoji associated with this category (leave empty if none)
        menuEmoji: ''

    # Category 2
    category2:
        # Label displayed in the select menu
        menuLabel: 'Category 2'
        # Description explaining the purpose of this category
        menuDescription: 'Use this category for technical support and troubleshooting.'
        # Emoji associated with this category (leave empty if none)
        menuEmoji: ''

    # Category 3
    category3:
        # Label displayed in the select menu
        menuLabel: 'Category 3'
        # Description explaining the purpose of this category
        menuDescription: 'For billing-related inquiries and payment issues.'
        # Emoji associated with this category (leave empty if none)
        menuEmoji: ''
