# ==============================================
# Ticket Bot General Settings
# ==============================================

# Maximum number of active tickets allowed per user
maxActiveTicketsPerUser: 1

# Inactivity threshold (in hours) after which tickets are closed automatically
ticketInactivityThreshold: 24

# The placeholder text for the select menu
menuPlaceholder: 'Select a category to open a ticket.'

# Roles with access to ticket channels
supportRoles:
    - '1228777265136140288' # Support role ID 1
    - '1220724757671182345' # Support role ID 2

# ID of the channel where ticket logs will be sent
logChannelId: '1242873167702265927'

# ID of the category under which ticket channels will be created
ticketCategoryId: '1240721969880760380' # Parent category ID for ticket channels

# ================================
# Ticket Category Settings
# ================================

# Define different categories of tickets here.
# Each category should have a unique identifier.

ticketCategories:
    # Category 1
    category1:
        # Label displayed in the select menu
        menuLabel: 'Category 1'
        # Description explaining the purpose of this category
        menuDescription: 'This category is for general inquiries and questions.'
        # Emoji associated with this category (leave empty if none)
        menuEmoji: '😀'
        # Embed description for this category
        embedDescription: 'Welcome to Category 1! Feel free to ask any general questions or make inquiries here.'

    # Category 2
    category2:
        # Label displayed in the select menu
        menuLabel: 'Category 2'
        # Description explaining the purpose of this category
        menuDescription: 'Use this category for technical support and troubleshooting.'
        # Emoji associated with this category (leave empty if none)
        menuEmoji: '🔧'
        # Embed description for this category
        embedDescription: 'Welcome to Category 2! Need technical support or facing any issues? Ask here.'

    # Category 3
    category3:
        # Label displayed in the select menu
        menuLabel: 'Category 3'
        # Description explaining the purpose of this category
        menuDescription: 'For billing-related inquiries and payment issues.'
        # Emoji associated with this category (leave empty if none)
        menuEmoji: '💳'
        # Embed description for this category
        embedDescription: 'Welcome to Category 3! Have any questions or issues regarding billing or payments? Let us know.'
